from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from typing import Callable, List


@dataclass
class EvalResult:
    faithfulness: float
    answer_relevance: float
    context_precision: float
    reasoning: dict[str, str]
    parse_errors: list[str] = field(default_factory=list)

    def passed(self, threshold: float = 0.7) -> bool:
        """Return True if all three scores meet the threshold.

        Useful as a boolean gate in CI pipelines:

            if not result.passed(threshold=0.8):
                raise ValueError("RAG quality below threshold")
        """
        return (
            self.faithfulness >= threshold
            and self.answer_relevance >= threshold
            and self.context_precision >= threshold
        )

    def __str__(self) -> str:
        lines = [
            f"  faithfulness      {self.faithfulness:.2f}  {self.reasoning.get('faithfulness', '')}",
            f"  answer_relevance  {self.answer_relevance:.2f}  {self.reasoning.get('answer_relevance', '')}",
            f"  context_precision {self.context_precision:.2f}  {self.reasoning.get('context_precision', '')}",
        ]
        if self.parse_errors:
            lines.append(f"  parse_errors      {self.parse_errors}")
        return "\n".join(lines)


def _format_contexts(contexts: List[str]) -> str:
    if not contexts:
        return "(no context provided)"
    return "\n".join(f"[{i+1}] {ctx}" for i, ctx in enumerate(contexts))


def _parse_llm_json(response: str) -> tuple[float, str, str | None]:
    """Parse LLM response into (score, reasoning, error).

    Returns a non-None error string if parsing failed — callers use this
    to populate EvalResult.parse_errors so silent failures are visible.
    """
    def extract(obj: dict) -> tuple[float, str, str | None]:
        score = float(obj.get("score", 0.0))
        score = max(0.0, min(1.0, score))
        reasoning = str(obj.get("reasoning", ""))
        return score, reasoning, None

    try:
        parsed = json.loads(response.strip())
        if isinstance(parsed, dict):
            return extract(parsed)
    except (json.JSONDecodeError, ValueError, TypeError):
        pass

    match = re.search(r'\{[^{}]*\}', response, re.DOTALL)
    if match:
        try:
            parsed = json.loads(match.group())
            if isinstance(parsed, dict):
                return extract(parsed)
        except (json.JSONDecodeError, ValueError, TypeError):
            pass

    error = f"JSON parse error: {response[:200]!r}"
    return 0.0, error, error


def _faithfulness_prompt(question: str, answer: str, contexts: List[str]) -> str:
    return f"""You are evaluating whether an answer is faithful to the provided context.

Question: {question}

Answer: {answer}

Context:
{_format_contexts(contexts)}

Score 1.0 if every claim in the answer is directly supported by the context.
Score 0.0 if the answer contains claims not found in the context.
Score between 0 and 1 proportionally for partial support.

Respond ONLY with valid JSON: {{"score": <float 0-1>, "reasoning": "<one sentence>"}}"""


def _answer_relevance_prompt(question: str, answer: str) -> str:
    return f"""You are evaluating whether an answer is relevant to the question asked.

Question: {question}

Answer: {answer}

Score 1.0 if the answer directly and completely addresses the question.
Score 0.0 if the answer is completely off-topic or refuses to answer.
Score between 0 and 1 for partial relevance.

Respond ONLY with valid JSON: {{"score": <float 0-1>, "reasoning": "<one sentence>"}}"""


def _context_precision_prompt(question: str, contexts: List[str]) -> str:
    return f"""You are evaluating whether the retrieved context is relevant and useful for answering the question.

Question: {question}

Context:
{_format_contexts(contexts)}

Score 1.0 if all context chunks are highly relevant to answering the question.
Score 0.0 if none of the context chunks are relevant.
Score between 0 and 1 proportionally based on the fraction of relevant chunks.

Respond ONLY with valid JSON: {{"score": <float 0-1>, "reasoning": "<one sentence>"}}"""


def evaluate(
    question: str,
    answer: str,
    contexts: List[str],
    llm_fn: Callable[[str], str],
) -> EvalResult:
    """
    Evaluate a RAG response across three metrics.

    Args:
        question: The user's original question.
        answer: The answer generated by the RAG system.
        contexts: The list of retrieved context chunks.
        llm_fn: Any callable that takes a prompt string and returns a string.

    Returns:
        EvalResult with faithfulness, answer_relevance, context_precision scores (0-1),
        per-metric reasoning strings, and a parse_errors list (non-empty if any metric
        failed to parse — a score of 0.0 with a parse error means the LLM response was
        unparseable, not that the answer was actually bad).
    """
    if not callable(llm_fn):
        raise TypeError(f"llm_fn must be callable, got {type(llm_fn).__name__!r}")
    if not isinstance(question, str) or not question.strip():
        raise ValueError("question must be a non-empty string")
    if not isinstance(answer, str) or not answer.strip():
        raise ValueError("answer must be a non-empty string")
    if not isinstance(contexts, list):
        raise TypeError(f"contexts must be a list, got {type(contexts).__name__!r}")

    faith_score, faith_reason, faith_err = _parse_llm_json(
        llm_fn(_faithfulness_prompt(question, answer, contexts))
    )
    relevance_score, relevance_reason, relevance_err = _parse_llm_json(
        llm_fn(_answer_relevance_prompt(question, answer))
    )
    precision_score, precision_reason, precision_err = _parse_llm_json(
        llm_fn(_context_precision_prompt(question, contexts))
    )

    parse_errors = [e for e in [faith_err, relevance_err, precision_err] if e is not None]

    return EvalResult(
        faithfulness=faith_score,
        answer_relevance=relevance_score,
        context_precision=precision_score,
        reasoning={
            "faithfulness": faith_reason,
            "answer_relevance": relevance_reason,
            "context_precision": precision_reason,
        },
        parse_errors=parse_errors,
    )
